app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, current_user
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitch = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)
        
    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)
            
    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref = 'role', lazy = "dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    '''
    Pitch class that define Pitch Objects
    '''
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch = db.Column(db.Text)
    category_id = db.Column(db.Integer)
    upvote = db.Column(db.Integer)
    downvote = db.Column(db.Integer)
    date = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_all_pitches(cls):
        return Pitch.query.all()

    @classmethod
    def get_pitches_by_category(cls,category_id):
        return Pitch.query.filter_by(category_id= category_id)


class Comment(db.Model):
    
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String)
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitch.id'))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save_comments(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(pitch_id=id).all()
        return comments

    @classmethod
    def clear_(cls):
        Comment.all_comments.clear()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Don\'t be shy... Tell us about yourself!',validators = [Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    category_id = SelectField('Which category best suits your new post?', choices=[('1', 'Pitches'), ('2', 'Pick-up Lines'), ('3', 'One-Liners')])
    content = TextAreaField('Create a post', validators=[Required()])
    submit = SubmitField('Submit') 

class CommentForm(FlaskForm):
    comment = StringField('Comment',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)
    mail.init_app(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import render_template, request, url_for, redirect, abort, flash
from flask_login import login_required, current_user
from . import main
from ..models import User, Pitch
from .forms import UpdateProfile, PitchForm
from .. import db, photos

@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    pitches = Pitch.get_all_pitches()
    title = 'Home'
    return render_template('index.html', pitches = pitches, title = title)

@main.route('/allposts')
def allposts():
    '''
    View allposts page function that returns the allposts page and its data
    '''
    title = 'All Posts'
    return render_template('pitches/allposts.html', title = title)

@main.route('/pitches')
def pitches():
    '''
    View pitches page function that returns the pitches page and its data
    '''
    pitches= Pitch.get_pitches_by_category(1)
    title = 'Pitches'
    return render_template('pitches/pitches.html', title = title, pitches = pitches)

@main.route('/pickuplines')
def pickuplines():
    '''
    View pickuplines page function that returns the pickuplines page and its data
    '''
    pitches= Pitch.get_pitches_by_category(2)
    title = 'Pick-up Lines'
    return render_template('pitches/pickuplines.html', title = title, pitches = pitches)

@main.route('/oneliners')
def oneliners():
    '''
    View oneliners page function that returns the oneliners page and its data
    '''
    pitches= Pitch.get_pitches_by_category(3)
    title = 'One-Liners'
    return render_template('pitches/oneliners.html', title = title, pitches = pitches)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    title = 'Profile'
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user, title = title)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    title = 'Update'
    if user is None:
        abort(404)
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',uname=user.username))
    return render_template('profile/update.html',form =form, title = title)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/new_post', methods = ['GET','POST'])
def new_post():
    form = PitchForm()
    title = 'New Post'
    if form.validate_on_submit():
        pitch = Pitch( category_id = form.category_id.data, pitch = form.content.data,)
        pitch.save_pitch()
        return redirect(url_for('main.index'))
    return render_template('/new_post.html',pitch_form = form, title = title)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block content %}

<style>
    h1 {color:#1a1a61; font-size: 380% ;text-decoration:underline ; font-weight: bold;}
    h2 {color:#1a1a61; font-size: 330%;}
    p {color:#0d1321; font-size: 200%; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif}
    .panel {background-color: #88B7B5; }
    .subtext {font-size: 130%; font-weight: bold;}
</style>

<div class="container text-center">
    <h1>Welcome to Pitch.com!</h1>
    <h2>Here are all our posts! Can you spot yours?</h2><br>
    <a href="{{url_for('main.new_post')}}"><br></a>
</div>


{% for pitch in pitches[::-1]%}
<div class="container">
    <div class="panel bg-light text-center style="style="box-shadow: 5px 5px 5px 5px #ceedec; padding:10px;">
        <p>"{{pitch.pitch}}"</p>
        <p class="subtext"> Posted: {{pitch.date.strftime("%c")}}</p>
        {{pitch.category_id}}
        <a class= "btn btn-success btn-sm" style="background-color: #7F7EFF;">Upvote </a>
        <a class= "btn btn-info btn-sm" style="background-color: #CC8B8C;">Downvote </a>
    </div>
</div>   
{% endfor %} 
{% endblock%}

app/templates/navbar.html
<style>
    li {color:#f2f2f2; font-size: 130%;}
</style>

  <nav class="navbar navbar-inverse" style="background:#0d1321" >
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Pitch.com</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/pitches">Pitches</a></li>
        <li><a href="/pickuplines">Pick-up Lines</a></li>
        <li><a href="/oneliners">One-Liners</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('main.new_post')}}">New Post</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
    </div>
  </nav>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="col-md-8"></div>
        <div class="col-md-4">
            {{ wtf.quick_form(review_form) }}
        </div>
    </div>
{% endblock %}

app/templates/new_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
 
    <div class="row">
        <div class="col-md-6 mx-auto">
            {{wtf.quick_form(pitch_form)}}
        </div>
    </div>
</div>
{% endblock%}

app/templates/pitches/allposts.html
{% extends 'base.html'%}
{% block content %}
{% endblock%}

app/templates/pitches/oneliners.html
{% extends 'base.html'%}
{% block content %}

<style>
    h1 {color:#1a1a61; font-size: 350% ;text-decoration:underline ; font-weight: bold;}
    h2 {color:#1a1a61; font-size: 300%;}
    p {color:#0d1321; font-size: 200%; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif}
    .panel {background-color: #88B7B5; }
    .subtext {font-size: 130%; font-weight: bold;}
</style>

<div class="container text-center">
    <h1>One-Liners</h1>
    <h2><em>Drops mic...</em></h2><br><br>
</div>

{% for pitch in pitches[::-1]%}
<div class="container">
        <div class="panel bg-light text-center style="style="box-shadow: 5px 5px 5px 5px #ceedec; padding:10px;">
            <p>"{{pitch.pitch}}"</p>
            <p class="subtext"> Posted: {{pitch.date.strftime("%c")}}</p>
            {{pitch.category_id}}
            <a class= "btn btn-success btn-sm" style="background-color: #7F7EFF;">Upvote </a>
          <a class= "btn btn-info btn-sm" style="background-color: #CC8B8C;">Downvote </a>
        </div>
    </div>
  {% endfor %} 
{% endblock%}

app/templates/pitches/pickuplines.html
{% extends 'base.html'%}
{% block content %}

<style>
    h1 {color:#1a1a61; font-size: 350% ;text-decoration:underline ; font-weight: bold;}
    h2 {color:#1a1a61; font-size: 300%;}
    p {color:#0d1321; font-size: 200%; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif}
    .panel {background-color: #88B7B5; }
    .subtext {font-size: 130%; font-weight: bold;}
</style>

<div class="container text-center">
    <h1>Pick-up Lines</h1>
    <h2><em>Tell them how you really feel boo...</em></h2><br><br>
</div>

{% for pitch in pitches[::-1]%}
<div class="container">
        <div class="panel bg-light text-center style="style="box-shadow: 5px 5px 5px 5px #ceedec; padding:10px;">
            <p>"{{pitch.pitch}}"</p>
            <p class="subtext"> Posted: {{pitch.date.strftime("%c")}}</p>
            {{pitch.category_id}}
            <a class= "btn btn-success btn-sm" style="background-color: #7F7EFF;">Upvote </a>
          <a class= "btn btn-info btn-sm" style="background-color: #CC8B8C;">Downvote </a>
        </div>
    </div>
  {% endfor %} 
{% endblock%}

app/templates/pitches/pitches.html
{% extends 'base.html'%}
{% block content %}

<style>
    h1 {color:#1a1a61; font-size: 350% ;text-decoration:underline ; font-weight: bold;}
    h2 {color:#1a1a61; font-size: 300%;}
    p {color:#0d1321; font-size: 200%; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif}
    .panel {background-color: #88B7B5; }
    .subtext {font-size: 130%; font-weight: bold;}
</style>

<div class="container text-center">
    <h1>Pitches</h1>
    <h2><em>For those trying to put a ding in the universe...in 140 characters or less.</em></h2><br><br>
</div>

{% for pitch in pitches[::-1]%}
<div class="container">
        <div class="panel bg-light text-center style="style="box-shadow: 5px 5px 5px 5px #ceedec; padding:10px;">
            <p>"{{pitch.pitch}}"</p>
            <p class="subtext"> Posted: {{pitch.date.strftime("%c")}}</p>
            {{pitch.category_id}}
            <a class= "btn btn-success btn-sm" style="background-color: #7F7EFF;">Upvote </a>
          <a class= "btn btn-info btn-sm" style="background-color: #CC8B8C;">Downvote </a>
        </div>
    </div>
  {% endfor %} 
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block styles%}

 {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">

{% endblock %}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-md-2">
            <h1 class="text-center"> {{user.username|capitalize}}</h1>

            {% if user.bio %}
            <h2 class="text-center"><em>"{{user.bio}}"</em></h2>
            {%else%}
            <p> {{user.username|capitalize}} has no bio </p>
            {% endif %}
        </div>

        <div class="col-md-8">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>
            {% endif %}

            {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
            <input type="file"  name="photo" class="form-control text-center" required>
            <input type="submit"><br><br>
            </form>
            {% endif %}
        </div>
        <div class="col-md-2">
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}"><h2 class="text-center"><u>Edit profile</u></h2>
            </a>
        {% endif %}
        <br>
        <a href="{{url_for('main.new_post')}}">
            <h2 class="text-center"><u>Create post</u></h2>
        </a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}